
development:
  adapter: postgresql
  encoding: unicode
  database: LauncherJournal_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: LauncherJournal_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: LauncherJournal_production
  pool: 5
  username:
  password:
